export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.4" }
  public: {
    Tables: {
      appointments: { Row: { created_at: string; duration_minutes: number; id: string; location_id: string; notes_status: string; patient_id: string; production_amount_cents: number; provider_id: string; scheduled_at: string; updated_at: string; visit_type: string; workflow_status: string }; Insert: { created_at?: string; duration_minutes?: number; id?: string; location_id: string; notes_status?: string; patient_id: string; production_amount_cents?: number; provider_id: string; scheduled_at: string; updated_at?: string; visit_type?: string; workflow_status: string }; Update: { created_at?: string; duration_minutes?: number; id?: string; location_id?: string; notes_status?: string; patient_id?: string; production_amount_cents?: number; provider_id?: string; scheduled_at?: string; updated_at?: string; visit_type?: string; workflow_status?: string }; Relationships: [] }
      communications: { Row: { channel: string; content: string; created_at: string; direction: string; id: string; organization_id: string; patient_id: string }; Insert: { channel: string; content: string; created_at?: string; direction: string; id?: string; organization_id: string; patient_id: string }; Update: { channel?: string; content?: string; created_at?: string; direction?: string; id?: string; organization_id?: string; patient_id?: string }; Relationships: [] }
      locations: { Row: { chair_count: number; city: string | null; created_at: string; daily_goal_cents: number; id: string; name: string; organization_id: string; updated_at: string }; Insert: { chair_count?: number; city?: string | null; created_at?: string; daily_goal_cents?: number; id?: string; name: string; organization_id: string; updated_at?: string }; Update: { chair_count?: number; city?: string | null; created_at?: string; daily_goal_cents?: number; id?: string; name?: string; organization_id?: string; updated_at?: string }; Relationships: [] }
      organizations: { Row: { created_at: string; id: string; name: string; updated_at: string }; Insert: { created_at?: string; id?: string; name: string; updated_at?: string }; Update: { created_at?: string; id?: string; name?: string; updated_at?: string }; Relationships: [] }
      patients: { Row: { balance_cents: number; created_at: string; date_of_birth: string | null; email: string | null; full_name: string; id: string; insurance_status: string; last_visit_date: string | null; location_id: string | null; no_show_risk: string; organization_id: string; phone: string | null; risk_score: number; treatment_plan_value_cents: number; updated_at: string }; Insert: { balance_cents?: number; created_at?: string; date_of_birth?: string | null; email?: string | null; full_name: string; id?: string; insurance_status?: string; last_visit_date?: string | null; location_id?: string | null; no_show_risk: string; organization_id: string; phone?: string | null; risk_score: number; treatment_plan_value_cents?: number; updated_at?: string }; Update: { balance_cents?: number; created_at?: string; date_of_birth?: string | null; email?: string | null; full_name?: string; id?: string; insurance_status?: string; last_visit_date?: string | null; location_id?: string | null; no_show_risk?: string; organization_id?: string; phone?: string | null; risk_score?: number; treatment_plan_value_cents?: number; updated_at?: string }; Relationships: [] }
      providers: { Row: { created_at: string; full_name: string; id: string; location_id: string | null; organization_id: string; specialty: string; updated_at: string }; Insert: { created_at?: string; full_name: string; id?: string; location_id?: string | null; organization_id: string; specialty?: string; updated_at?: string }; Update: { created_at?: string; full_name?: string; id?: string; location_id?: string | null; organization_id?: string; specialty?: string; updated_at?: string }; Relationships: [] }
      tasks: { Row: { appointment_id: string; completed: boolean; created_at: string; id: string; title: string; updated_at: string }; Insert: { appointment_id: string; completed?: boolean; created_at?: string; id?: string; title: string; updated_at?: string }; Update: { appointment_id?: string; completed?: boolean; created_at?: string; id?: string; title?: string; updated_at?: string }; Relationships: [] }
      visitor_names: { Row: { anonymous_id: string; created_at: string; id: string; name: string; updated_at: string }; Insert: { anonymous_id: string; created_at?: string; id?: string; name: string; updated_at?: string }; Update: { anonymous_id?: string; created_at?: string; id?: string; name?: string; updated_at?: string }; Relationships: [] }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]) | { schema: keyof DatabaseWithoutInternals }, TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"]) : never = never> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends { Row: infer R } ? R : never : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]) ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends { Row: infer R } ? R : never : never

export type TablesInsert<DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals }, TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] : never = never> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends { Insert: infer I } ? I : never : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Insert: infer I } ? I : never : never

export type TablesUpdate<DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals }, TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] : never = never> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends { Update: infer U } ? U : never : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Update: infer U } ? U : never : never

export type Enums<DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals }, EnumName extends DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"] : never = never> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName] : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"] ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions] : never

export type CompositeTypes<PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals }, CompositeTypeName extends PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"] : never = never> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName] : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"] ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions] : never

export const Constants = { public: { Enums: {} } } as const
